#!/bin/bash
# Uncomment as needed


# echo "Delete love files in this directory? y or n"

# read answer

# if [ "$answer" != "${answer#[Yy]}" ] ;then
#     rm *.love
# else
#     echo Cancel
# fi


echo "Deleting love files in this directory"
rm *.love
exit 1
