#!/bin/bash

echo "What kinda file?"
read varf
echo "And the website?"
read varw

wget -r -1 --no-parent --accept=$varf $varw

#  _______________
# |@@@@|     |####|
# |@@@@|     |####|
# |@@@@|     |####|
# \@@@@|     |####/
#  \@@@|     |###/
#   `@@|_____|##'
#        (O)
#     .-'''''-.
#   .'  * * *  `.
#  :  *       *  :
# :  ~~~~Colt~~~~~:
# :  ~~~~KIRK~~~~~:
#  :  *       *  :
#   `.  * * *  .'
#     `-.....-'
#
